openapi: 3.0.0
info:
  title: Sable
  description: MongoDB ExpressJS NodeJS REST API
  version: 1.0.0
servers:
  - url: https://sableplan.herokuapp.com/
    description: Heroku remote server
  - url: http://localhost:4000/
    description: Localhost development server
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: auth-token

  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        color:
          type: string
        deadline:
          type: string

    List:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        color:
          type: string

    Task:
      type: object
      properties:
        id:
          type: string
        task:
          type: string
        description:
          type: string
        status:
          type: string
        deadline:
          type: string
        author:
          type: string

    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        pass:
          type: string
        userLevel:
          type: string
          

paths:
  /users/register:
    post:
      tags:
        - Users
      summary: Register User
      description: Register a new User in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        201:
          description: User created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  _id:
                    type: string

  /users/login:
    post:
      tags:
        - Users
      summary: Login User
      description: Login a User in order to get JWT token (auth-token)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                pass:
                  type: string

      responses:
        200:
          description: User logged in succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: string

  /users:
    get:
      tags:
        - Users
      summary: View All Users
      description: Retrieves a list of Users.
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: A list of Users in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

  /tasks:
    post:
      tags:
        - Tasks
      summary: Add New Task
      description: Add a new Task
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"

      responses:
        201:
          description: Task added succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    
    get:
      tags:
        - Tasks
      summary: View All Tasks
      description: Retrieves a list of Tasks as objects.
      responses:
        200:
          description: A list of Task objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

  /tasks/{id}:
    get:
      tags:
        - Tasks
      summary: View Specific Task
      description: Retrieves a specific Task based on its id.
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      responses:
        200:
          description: A Task in the format of an object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

    put:
      tags:
        - Tasks
      summary: Edit Task Information
      description: Updates a specific Task based on its id
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"

      responses:
        201:
          description: Task updated succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"

    delete:
      tags:
        - Tasks
      summary: Delete Task
      description: Deletes a specific Task based on it id
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string

      responses:
        201:
          description: Task deleted succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
  
  /lists:
    post:
      tags:
        - Lists
      summary: Add New List
      description: Add a new List
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/List"

      responses:
        201:
          description: List added succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/List"
    
    get:
      tags:
        - Lists
      summary: View All Lists
      description: Retrieves a list of Lists as objects.
      responses:
        200:
          description: A list of List objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/List"

  /lists/{id}:
    get:
      tags:
        - Lists
      summary: View Specific List
      description: Retrieves a specific List based on its id.
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      responses:
        200:
          description: A List in the format of an object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/List"

    put:
      tags:
        - Lists
      summary: Edit List Information
      description: Updates a specific List based on its id
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/List"

      responses:
        201:
          description: List updated succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/List"

    delete:
      tags:
        - Lists
      summary: Delete List
      description: Deletes a specific List based on it id
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string

      responses:
        201:
          description: List deleted succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/List"
  
  /projects:
    post:
      tags:
        - Projects
      summary: Add New Project
      description: Add a new Project
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"

      responses:
        201:
          description: Project added succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
    
    get:
      tags:
        - Projects
      summary: View All Projects
      description: Retrieves a list of Projects as objects.
      responses:
        200:
          description: A list of Project objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"

  /projects/{id}:
    get:
      tags:
        - Projects
      summary: View Specific Project
      description: Retrieves a specific Project based on its id.
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      responses:
        200:
          description: A Project in the format of an object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"

    put:
      tags:
        - Projects
      summary: Edit Project Information
      description: Updates a specific Project based on its id
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"

      responses:
        201:
          description: Project updated succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"

    delete:
      tags:
        - Projects
      summary: Delete Project
      description: Deletes a specific Project based on it id
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string

      responses:
        201:
          description: Project deleted succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
